import type { POI } from '../shared/types'

export const pois: POI[] = [
  {
    id: 'kasthamandap',
    name: 'Kasthamandap',
    category: 'heritage temple',
    lat: 27.704,
    lng: 85.30583,
    radius_m: 45,
    image_url: 'https://picsum.photos/seed/kasthamandap/1200/800',
    short_hook: 'The wooden shrine that gave Kathmandu its name.',
    history: 'Kasthamandap began as a Licchavi-era wooden shelter and later became one of the most important structures in Kathmandu Durbar Square. It was badly damaged in the 2015 earthquake and rebuilt afterward.',
    folklore: 'Local tradition says the shelter was built from a single tree and associated with Gorakshanath, the yogi whose presence blessed the site.',
    culture_note: 'People still gather here during visits to Durbar Square, and it remains a landmark of Newar craftsmanship and civic memory.',
  },
  {
    id: 'taleju-temple',
    name: 'Taleju Temple',
    category: 'temple',
    lat: 27.704871,
    lng: 85.308008,
    radius_m: 40,
    image_url: 'https://picsum.photos/seed/taleju-temple/1200/800',
    short_hook: 'The royal temple of Taleju Bhawani inside Kathmandu Durbar Square.',
    history: 'Built in 1564 by Mahendra Malla, Taleju Temple sits within Hanuman Dhoka and reflects the power of the Malla court. It was originally a royal shrine, not a public temple.',
    folklore: 'Legend ties the temple to the Malla kings and the living goddess Kumari, with the deity protected so only select people may enter.',
    culture_note: 'It is still opened on special ritual days, especially during Dashain, when worshippers and royal traditions briefly return to the square.',
  },
  {
    id: 'kumari-ghar',
    name: 'Kumari Ghar',
    category: 'palace',
    lat: 27.703722,
    lng: 85.306472,
    radius_m: 35,
    image_url: 'https://picsum.photos/seed/kumari-ghar/1200/800',
    short_hook: 'The residence of Kathmandu’s Living Goddess.',
    history: 'Kumari Ghar is the ornate palace where the living goddess Kumari resides in Kathmandu Durbar Square. The present building dates to the Malla period and remains one of the square’s most visited heritage houses.',
    folklore: 'Tradition says the Kumari is chosen as a living embodiment of Taleju, and her brief appearances are treated as highly auspicious blessings.',
    culture_note: 'Visitors still gather outside the courtyard to see the palace facade and to catch a glimpse of the Kumari during public appearances and festival processions.',
  },
  {
    id: 'hanuman-dhoka',
    name: 'Hanuman Dhoka',
    category: 'palace complex',
    lat: 27.7042,
    lng: 85.3075,
    radius_m: 55,
    image_url: 'https://picsum.photos/seed/hanuman-dhoka/1200/800',
    short_hook: 'The old royal palace complex at the heart of Kathmandu Durbar Square.',
    history: 'Hanuman Dhoka was the royal seat of the Malla and later Shah rulers. Its courtyards, gates, and museums preserve layers of palace history from the 16th century onward.',
    folklore: 'The main gate is guarded by Hanuman, whose image gave the palace its name, and local legend says the sacred threshold protects the kingdom.',
    culture_note: 'It now functions as a historic museum and ceremonial site, with courtyards, shrines, and festival spaces still active today.',
  },
  {
    id: 'bhagwati-temple',
    name: 'Bhagwati Temple',
    category: 'temple',
    lat: 27.70493,
    lng: 85.30736,
    radius_m: 28,
    image_url: 'https://picsum.photos/seed/bhagwati-temple/1200/800',
    short_hook: 'A compact sacred shrine tied to the religious life of the old royal square.',
    history: 'Bhagwati Temple is part of the dense ritual landscape around Kathmandu Durbar Square, where royal and public worship traditions have long overlapped. The shrine reflects the layered Hindu devotional culture that grew around the palace area over centuries.',
    folklore: 'Local stories link the temple to protective goddess energy, with devotees treating the shrine as a place for blessing, safety, and auspicious beginnings.',
    culture_note: 'It remains one of the smaller but important spiritual stops in the square, especially for visitors interested in the living religious fabric of the site.',
  },
  {
    id: 'jagannath-temple',
    name: 'Jagannath Temple',
    category: 'temple',
    lat: 27.70455,
    lng: 85.30691,
    radius_m: 26,
    image_url: 'https://picsum.photos/seed/jagannath-temple/1200/800',
    short_hook: 'An iconic temple known for its historic craftsmanship and square-side presence.',
    history: 'Jagannath Temple is one of the notable religious structures associated with Kathmandu Durbar Square, representing the artistic and devotional traditions of the Malla period. Its place in the square connects it to the wider temple-palace network that defined the old city center.',
    folklore: 'The temple is often remembered through local stories about divine protection and the sacred atmosphere of the square, where every structure carries a ritual meaning beyond architecture.',
    culture_note: 'It is a strong example of how the square is not just a monument zone but an active religious landscape with deep cultural continuity.',
  },
  {
    id: 'shiva-parvati-temple',
    name: 'Shiva Parvati Temple',
    category: 'temple',
    lat: 27.70437,
    lng: 85.30662,
    radius_m: 30,
    image_url: 'https://picsum.photos/seed/shiva-parvati-temple/1200/800',
    short_hook: 'A beloved shrine with a highly recognizable presence in the Durbar Square complex.',
    history: 'Shiva Parvati Temple is one of the intimate temple spaces around Kathmandu Durbar Square, reflecting the Hindu sacred architecture that developed alongside the royal palaces. Its presence adds to the square’s layered visual and spiritual rhythm.',
    folklore: 'The temple is associated with divine couple imagery, and local tradition sees it as a peaceful, auspicious place within the busier royal environment.',
    culture_note: 'Visitors often notice it as a compact but memorable stop, especially because it reinforces how the square blends civic history with lived devotion.',
  },
  {
    id: 'old-royal-palace-courtyard',
    name: 'Old Royal Palace Courtyard',
    category: 'palace complex',
    lat: 27.70418,
    lng: 85.30718,
    radius_m: 45,
    image_url: 'https://picsum.photos/seed/old-royal-palace-courtyard/1200/800',
    short_hook: 'The open courtyard core where royal life, ceremony, and daily movement once converged.',
    history: 'The old royal palace courtyard area formed the functional heart of the palace complex, linking audience halls, ritual spaces, and administrative rooms. It represents the spatial logic of Kathmandu’s royal center more than a single monument.',
    folklore: 'Court stories and palace legends often frame the courtyard as a threshold space where power, ritual, and public spectacle intersected.',
    culture_note: 'Today it helps visitors understand the palace as a living compound rather than a single building, making it one of the most important interpretive spaces in Durbar Square.',
  },
]
