import type { POI } from '../shared/types'

export const pois: POI[] = [
  {
    id: 'kasthamandap',
    name: 'Kasthamandap',
    category: 'heritage temple',
    lat: 27.704,
    lng: 85.30583,
    radius_m: 45,
    short_hook: 'The wooden shrine that gave Kathmandu its name.',
    history: 'Kasthamandap began as a Licchavi-era wooden shelter and later became one of the most important structures in Kathmandu Durbar Square. It was badly damaged in the 2015 earthquake and rebuilt afterward.',
    folklore: 'Local tradition says the shelter was built from a single tree and associated with Gorakshanath, the yogi whose presence blessed the site.',
    culture_note: 'People still gather here during visits to Durbar Square, and it remains a landmark of Newar craftsmanship and civic memory.',
  },
  {
    id: 'taleju-temple',
    name: 'Taleju Temple',
    category: 'temple',
    lat: 27.704871,
    lng: 85.308008,
    radius_m: 40,
    short_hook: 'The royal temple of Taleju Bhawani inside Kathmandu Durbar Square.',
    history: 'Built in 1564 by Mahendra Malla, Taleju Temple sits within Hanuman Dhoka and reflects the power of the Malla court. It was originally a royal shrine, not a public temple.',
    folklore: 'Legend ties the temple to the Malla kings and the living goddess Kumari, with the deity protected so only select people may enter.',
    culture_note: 'It is still opened on special ritual days, especially during Dashain, when worshippers and royal traditions briefly return to the square.',
  },
  {
    id: 'kumari-ghar',
    name: 'Kumari Ghar',
    category: 'palace',
    lat: 27.703722,
    lng: 85.306472,
    radius_m: 35,
    short_hook: 'The residence of Kathmandu’s Living Goddess.',
    history: 'Kumari Ghar is the ornate palace where the living goddess Kumari resides in Kathmandu Durbar Square. The present building dates to the Malla period and remains one of the square’s most visited heritage houses.',
    folklore: 'Tradition says the Kumari is chosen as a living embodiment of Taleju, and her brief appearances are treated as highly auspicious blessings.',
    culture_note: 'Visitors still gather outside the courtyard to see the palace facade and to catch a glimpse of the Kumari during public appearances and festival processions.',
  },
  {
    id: 'hanuman-dhoka',
    name: 'Hanuman Dhoka',
    category: 'palace complex',
    lat: 27.7042,
    lng: 85.3075,
    radius_m: 55,
    short_hook: 'The old royal palace complex at the heart of Kathmandu Durbar Square.',
    history: 'Hanuman Dhoka was the royal seat of the Malla and later Shah rulers. Its courtyards, gates, and museums preserve layers of palace history from the 16th century onward.',
    folklore: 'The main gate is guarded by Hanuman, whose image gave the palace its name, and local legend says the sacred threshold protects the kingdom.',
    culture_note: 'It now functions as a historic museum and ceremonial site, with courtyards, shrines, and festival spaces still active today.',
  },
]
